apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sta
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: sta
spec:
  source:
    git:
      url: https://github.com/alexandreroman/sta.git
      ref:
        branch: main
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi
      cpu: 250m
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
      autoscaling.knative.dev/maxScale: "3"
      autoscaling.knative.dev/target: "100"
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/window: "300s"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: skip
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: /api/openapi
      owner: default/sta-team
      system: default/sta
      description: STA API
  env:
  - name: STA_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
