apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sta-invoker
  description: Trading Agent Invoker
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=sta-invoker
spec:
  type: service
  lifecycle: experimental
  owner: sta-team
  system: sta
