apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sta-marketplace
  description: Marketplace
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=sta-marketplace
spec:
  type: service
  lifecycle: experimental
  owner: sta-team
  system: sta
  dependsOn:
  - resource:sta-broker
  - resource:sta-marketplace-db
